# Generated by Django 3.1.4 on 2020-12-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamTokenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, verbose_name='channel name')),
                ('rol_user', models.PositiveIntegerField(verbose_name='rol user')),
            ],
        ),
        migrations.CreateModel(
            name='UserStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, verbose_name='name_user')),
                ('uidd', models.PositiveIntegerField(verbose_name='uuid')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream_control.streamtokenuser')),
            ],
        ),
    ]
